name: maat-dev

x-node: &node
  build:
    context: .
  init: true
  restart: "no"
  stop_grace_period: 30s
  secrets:
    - postgres-password
    - replication-password

services:
  instance-a:
    <<: *node
    hostname: instance-a
    labels:
      maat.cluster: maat_dev
      maat.node: instance-a
    volumes:
      - instance-a-data:/var/lib/maat/postgres
      - instance-a-control:/var/lib/maat/control
      - ./deploy/instance-a.json:/etc/maat/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:15432:5432"
      - "127.0.0.1:18080:8000"
  instance-b:
    <<: *node
    hostname: instance-b
    labels:
      maat.cluster: maat_dev
      maat.node: instance-b
    volumes:
      - instance-b-data:/var/lib/maat/postgres
      - instance-b-control:/var/lib/maat/control
      - ./deploy/instance-b.json:/etc/maat/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:15433:5432"
      - "127.0.0.1:18081:8000"
  instance-c:
    <<: *node
    hostname: instance-c
    labels:
      maat.cluster: maat_dev
      maat.node: instance-c
    volumes:
      - instance-c-data:/var/lib/maat/postgres
      - instance-c-control:/var/lib/maat/control
      - ./deploy/instance-c.json:/etc/maat/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:15434:5432"
      - "127.0.0.1:18082:8000"

volumes:
  instance-a-data:
  instance-a-control:
  instance-b-data:
  instance-b-control:
  instance-c-data:
  instance-c-control:

secrets:
  postgres-password:
    file: ./.secrets/postgres-password
  replication-password:
    file: ./.secrets/replication-password
